version: "3"

services:
  fail2ban:
    image: docker.io/crazymax/fail2ban:latest
    init: true
    container_name: fail2ban
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - "./data:/data:rw"
      - "/var/log:/var/log:ro"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
        compress: "true"
